config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  get '/add_bird_records', to: 'birding_sessions#new'
  resources :birding_sessions, only: [:new, :create, :edit, :update, :show]

  resources :clubs
  post '/clubs/:id/join', to: 'clubs#join', as: 'join_club'
  post '/clubs/:id/leave', to: 'clubs#leave', as: 'leave_club'
  get '/clubs/:id/members', to: 'clubs#members', as: 'club_members'
  get '/clubs/:id/membership', to: 'clubs#membership', as: 'club_membership'
  post '/clubs/:id/members/:user_id/roles', to: 'clubs#update_roles', as: 'update_club_roles'

  resources :photos, only: [:new, :create, :destroy]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  get 'user/clubs', to: 'user#clubs', as: 'user_clubs'

  get '/bird_lists/birds', to: 'bird_lists#birds'

  namespace :admin do
    root to: 'welcome#index'

    resources :bird_list_birds
    resources :bird_lists
    resources :bird_records
    resources :birding_sessions
    resources :birds
    resources :club_memberships
    resources :clubs
    resources :rarities
    resources :users

    mount Resque::Server.new, :at => "/resque"
  end

  root to: 'welcome#index'
end

app/models/birding_session.rb
# == Schema Information
#
# Table name: birding_sessions
#
#  id                :integer          not null, primary key
#  date              :date
#  location          :geography({:srid point, 4326
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  user_id           :integer
#  location_name     :string           not null
#  weather_report_id :integer
#  time              :time
#  country_code      :string(2)        not null
#

class BirdingSession < ApplicationRecord
  belongs_to :user
  belongs_to :weather_report, optional: true

  has_many :birds, through: :bird_records
  has_many :bird_records, dependent: :destroy
  has_many :photos, through: :bird_records

  accepts_nested_attributes_for :bird_records

  validates :bird_records, presence: true
  validates :date, presence: true
  validates :location, presence: true
  validates :time, presence: true

  def country_name
    country.local_name
  end

  def datetime
    return nil if date.nil? or time.nil?
    @datetime ||= DateTime.new(date.year, date.month, date.day, time.hour, time.min, time.sec, time.zone)
  end

  def latitude
    location.lat
  end

  def longitude
    location.lon
  end

  def to_s
    "#{date} - #{location_name}"
  end

  def user_name
    user.full_name
  end

  private

  def country
    @country ||= ISO3166::Country.new(country_code)
  end
end

app/controllers/admin/birding_session_controller.rb
class Admin::BirdingSessionController < ApplicationController
  # GET /admin/birding_sessions
  def index
    @birding_sessions = BirdingSession.all.page(params[:page])
  end

  # GET /admin/birding_sessions/1
  def show
    @birding_session = BirdingSession.find(params[:id])
  end

  # GET /admin/birding_sessions/new
  def new
    @birding_session = BirdingSession.new
  end

  # GET /admin/birding_sessions/1/edit
  def edit
    @birding_session = BirdingSession.find(params[:id])
  end

  # POST /admin/birding_sessions
  def create
    @birding_session = BirdingSession.new(birding_session_params)

    if @birding_session.save
      redirect_to admin_birding_sessions_url, notice: 'Birding session was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/birding_sessions/1
  def update
    @birding_session = BirdingSession.find(params[:id])

    if @birding_session.update(birding_session_params)
      redirect_to admin_birding_sessions_url, notice: 'Birding session was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/birding_sessions/1
  def destroy
    @birding_session = BirdingSession.find(params[:id])

    @birding_session.destroy
    redirect_to admin_birding_sessions_url, notice: 'Birding session was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def birding_session_params
      params.require(:birding_session).permit(:date, :location, :user_id)
    end
end

app/controllers/admin/birding_sessions_controller.rb
class Admin::BirdingSessionsController < ApplicationController
  # GET /admin/birding_sessions
  def index
    @birding_sessions = BirdingSession.all.page(params[:page])
  end

  # GET /admin/birding_sessions/1
  def show
    @birding_session = BirdingSession.find(params[:id])
  end

  # GET /admin/birding_sessions/new
  def new
    @birding_session = BirdingSession.new
  end

  # GET /admin/birding_sessions/1/edit
  def edit
    @birding_session = BirdingSession.find(params[:id])
  end

  # POST /admin/birding_sessions
  def create
    @birding_session = BirdingSession.new(birding_session_params)

    if @birding_session.save
      redirect_to admin_birding_sessions_url, notice: 'Birding session was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/birding_sessions/1
  def update
    @birding_session = BirdingSession.find(params[:id])

    if @birding_session.update(birding_session_params)
      redirect_to admin_birding_sessions_url, notice: 'Birding session was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/birding_sessions/1
  def destroy
    @birding_session = BirdingSession.find(params[:id])

    @birding_session.destroy
    redirect_to admin_birding_sessions_url, notice: 'Birding session was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def birding_session_params
      params.require(:birding_session).permit(:date, :time, :location, :location_name, :country_code, :user_id)
    end
end

app/controllers/birding_sessions_controller.rb
class BirdingSessionsController < ApplicationController
  # GET /birding_sessions/:id
  # GET /birding_sessions/:id.json
  def show
    @birding_session = BirdingSession.includes(bird_records: :bird).find(params[:id])
  end

  # GET /birding_sessions/new
  def new
    @birding_session = current_user.birding_sessions.new
  end

  # POST /birding_sessions
  # POST /birding_sessions.json
  def create
    @birding_session = BirdingSession.new(birding_session_params)

    respond_to do |format|
      if @birding_session.save
        run_background_jobs

        format.html { redirect_to @birding_session, notice: 'Bird records were successfully created.' }
        format.json { render :show, status: :created, location: @birding_session }
      else
        format.html { render :new }
        format.json { render json: @birding_session.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @birding_session = BirdingSession
      .includes(bird_records: :photos)
      .order('bird_records.created_at')
      .find(params[:id])
  end

  def update
    @birding_session = BirdingSession.find(params[:id])

    respond_to do |format|
      if @birding_session.update(birding_session_params)
        run_background_jobs

        format.html { redirect_to @birding_session, notice: "Bird records successfully updated." }
        format.json { render :show, status: :ok, location: @birding_session }
      else
        format.html { render :edit }
        format.json { render json: @birding_session.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def birding_session_params
      params.require(:birding_session).permit(:date, :time, :location, :location_name, :country_code, :user_id, :bird_records_attributes => [:id, :bird_id, :count, :notes, :time, :location, :photo_ids => []])
    end

    def run_background_jobs
      # Lookup the weather for this birding session
      WeatherForecastJob.perform_later @birding_session
      # Add any records to clubs
      UpdateClubRecordsJob.perform_later @birding_session
    end
end

app/views/admin/birding_sessions/_form.html.erb
<%= simple_form_for([:admin, @birding_session]) do |f| %>
  <%= f.error_notification %>

    <%= f.input :date %>
    <%= f.input :time %>
    <%= f.input :location_name %>
    <%= f.input :location, as: :string %>
    <%= f.association :user %>

  <%= f.button :submit %>
<% end %>

app/views/admin/birding_sessions/edit.html.erb
<%= page_header "Editing #{@birding_session.to_s}" %>

<div class="container">
  <div class="row">
  <div class="col-4">
      <%= render 'form', birding_session: @birding_session %>
    </div>
  </div>
</div>

app/views/admin/birding_sessions/index.html.erb
<%= page_header "Birding Sessions" %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <table class="table table-responsive">
        <thead>
          <tr>
            <th>Date</th>
            <th>Start Time</th>
            <th>Location</th>
            <th>User</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @birding_sessions.each do |birding_session| %>
            <tr>
              <td><%= birding_session.date %></td>
              <td><%= birding_session.time %></td>
              <td><%= birding_session.location_name %></td>
              <td><%= birding_session.user %></td>
              <td class="text-right">
              <%= link_to 'Show', [:admin ,birding_session], class: 'text-dark' %> |
              <%= link_to 'Edit', [:edit, :admin ,birding_session], class: 'text-dark' %> |
              <%= link_to 'Destroy', [:admin ,birding_session], method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= paginate @birding_sessions %>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <%= link_to 'Create New Birding Session', new_admin_birding_session_path, class: 'btn btn-outline-primary' %>
    </div>
  </div>
</div>

app/views/admin/birding_sessions/new.html.erb
<%= page_header "New Birding Session" %>

<div class="container">
  <div class="row">
    <div class="col-4">
      <%= render 'form', birding_session: @birding_session %>
    </div>
  </div>
</div>

app/views/admin/birding_sessions/show.html.erb
<%= page_header @birding_session %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <dl class="row">
        <dt class="col-sm-3">Date</dt>
        <dd class="col-sm-9"><%= @birding_session.date %></dd>
      </dl>
    <div class="col-12">
      <dl class="row">
        <dt class="col-sm-3">Start Time</dt>
        <dd class="col-sm-9"><%= @birding_session.time %></dd>
      </dl>
    <div class="col-12">
      <dl class="row">
        <dt class="col-sm-3">Location Name</dt>
        <dd class="col-sm-9"><%= @birding_session.location_name %></dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">Location</dt>
        <dd class="col-sm-9"><%= @birding_session.location %></dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">User</dt>
        <dd class="col-sm-9"><%= link_to @birding_session.user, [:admin, @birding_session.user] %></dd>
      </dl>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <%= link_to 'Edit', [:edit, :admin, @birding_session], class: 'btn btn-outline-dark' %>
      <%= link_to 'Destroy', [:admin, @birding_session], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </div>
  </div>
</div>