config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  get '/add_bird_records', to: 'birding_sessions#new'
  resources :birding_sessions, only: [:new, :create, :edit, :update, :show]

  resources :clubs
  post '/clubs/:id/join', to: 'clubs#join', as: 'join_club'
  post '/clubs/:id/leave', to: 'clubs#leave', as: 'leave_club'
  get '/clubs/:id/members', to: 'clubs#members', as: 'club_members'
  get '/clubs/:id/membership', to: 'clubs#membership', as: 'club_membership'
  post '/clubs/:id/members/:user_id/roles', to: 'clubs#update_roles', as: 'update_club_roles'

  resources :photos, only: [:new, :create, :destroy]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  get 'user/clubs', to: 'user#clubs', as: 'user_clubs'

  get '/bird_lists/birds', to: 'bird_lists#birds'

  namespace :admin do
    root to: 'welcome#index'

    resources :bird_list_birds
    resources :bird_lists
    resources :bird_records
    resources :birding_sessions
    resources :birds
    resources :club_memberships
    resources :clubs
    resources :rarities
    resources :users

    mount Resque::Server.new, :at => "/resque"
  end

  root to: 'welcome#index'
end

app/models/bird_list.rb
# == Schema Information
#
# Table name: bird_lists
#
#  id           :integer          not null, primary key
#  name         :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  bounding_box :geography({:srid polygon, 4326
#  club_id      :integer
#

class BirdList < ApplicationRecord
  include Geographical

  has_many :bird_list_birds
  has_many :birds, through: :bird_list_birds

  scope :covering, -> (lng, lat) { where('ST_Intersects(bounding_box, ?)', create_point(lng, lat)) }
  scope :order_by_area, -> { order('ST_Area(bounding_box)') }

  def to_s
    name
  end
end

app/controllers/admin/bird_lists_controller.rb
class Admin::BirdListsController < ApplicationController
  # GET /bird_lists
  def index
    @bird_lists = BirdList.all.page(params[:page])
  end

  # GET /bird_lists/1
  def show
    @bird_list = BirdList.find(params[:id])
  end

  # GET /bird_lists/new
  def new
    @bird_list = BirdList.new
  end

  # GET /bird_lists/1/edit
  def edit
    @bird_list = BirdList.find(params[:id])
  end

  # POST /bird_lists
  def create
    @bird_list = BirdList.new(bird_list_params)

    if @bird_list.save
      redirect_to admin_bird_lists_url, notice: 'Bird list was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /bird_lists/1
  def update
    @bird_list = BirdList.find(params[:id])
    if @bird_list.update(bird_list_params)
      redirect_to admin_bird_lists_url, notice: 'Bird list was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bird_lists/1
  def destroy
    @bird_list = BirdList.find(params[:id])

    @bird_list.destroy
    redirect_to admin_bird_lists_url, notice: 'Bird list was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def bird_list_params
      params.require(:bird_list).permit(:name, :bounding_box)
    end
end

app/controllers/bird_lists_controller.rb
class BirdListsController < ApplicationController
  def birds
    lng, lat = params[:lng], params[:lat]

    @bird_list = BirdList.covering(lng, lat)
      .order_by_area
      .first

    @birds = @bird_list.bird_list_birds
      .ioc_order
      .includes(:rarity, :bird)
  end
end

app/helpers/bird_lists_helper.rb
module BirdListsHelper
end

app/views/admin/bird_lists/_form.html.erb
<%= simple_form_for([:admin, @bird_list]) do |f| %>
  <%= f.error_notification %>

    <%= f.input :name %>
    <%= f.input :bounding_box, as: :string %>

  <%= f.button :submit %>
<% end %>

app/views/admin/bird_lists/edit.html.erb
<%= page_header "Editing #{@bird_list.to_s}" %>

<div class="container">
  <div class="row">
  <div class="col-4">
      <%= render 'form', bird_list: @bird_list %>
    </div>
  </div>
</div>

app/views/admin/bird_lists/index.html.erb
<%= page_header "Bird Lists" %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <table class="table table-responsive">
        <thead>
          <tr>
            <th>Name</th>
            <th>Birds</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @bird_lists.each do |bird_list| %>
            <tr>
              <td><%= bird_list.name %></td>
              <td><%= bird_list.birds.count %></td>
              <td class="text-right">
              <%= link_to 'Show', [:admin, bird_list], class: 'text-dark' %> |
              <%= link_to 'Edit', [:edit, :admin, bird_list], class: 'text-dark' %> |
              <%= link_to 'Destroy', [:admin, bird_list], method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= paginate @bird_lists %>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <%= link_to 'Create New Bird List', new_admin_bird_list_path, class: 'btn btn-outline-primary' %>
    </div>
  </div>
</div>

app/views/admin/bird_lists/new.html.erb
<%= page_header "New Bird List" %>

<div class="container">
  <div class="row">
    <div class="col-4">
      <%= render 'form', bird_list: @bird_list %>
    </div>
  </div>
</div>

app/views/admin/bird_lists/show.html.erb
<%= page_header @bird_list %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <dl class="row">
        <dt class="col-sm-3">Name</dt>
        <dd class="col-sm-9"><%= @bird_list.name %></dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">Bounding Box</dt>
        <dd class="col-sm-9"><%= @bird_list.bounding_box %></dd>
      </dl>
          </div>
  </div>
  <div class="row">
    <div class="col-12">
      <%= link_to 'Edit', [:edit, :admin, @bird_list], class: 'btn btn-outline-dark' %>
      <%= link_to 'Destroy', [:admin, @bird_list], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </div>
  </div>
</div>