config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  get '/add_bird_records', to: 'birding_sessions#new'
  resources :birding_sessions, only: [:new, :create, :edit, :update, :show]

  resources :clubs
  post '/clubs/:id/join', to: 'clubs#join', as: 'join_club'
  post '/clubs/:id/leave', to: 'clubs#leave', as: 'leave_club'
  get '/clubs/:id/members', to: 'clubs#members', as: 'club_members'
  get '/clubs/:id/membership', to: 'clubs#membership', as: 'club_membership'
  post '/clubs/:id/members/:user_id/roles', to: 'clubs#update_roles', as: 'update_club_roles'

  resources :photos, only: [:new, :create, :destroy]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  get 'user/clubs', to: 'user#clubs', as: 'user_clubs'

  get '/bird_lists/birds', to: 'bird_lists#birds'

  namespace :admin do
    root to: 'welcome#index'

    resources :bird_list_birds
    resources :bird_lists
    resources :bird_records
    resources :birding_sessions
    resources :birds
    resources :club_memberships
    resources :clubs
    resources :rarities
    resources :users

    mount Resque::Server.new, :at => "/resque"
  end

  root to: 'welcome#index'
end

app/models/bird_record.rb
# == Schema Information
#
# Table name: bird_records
#
#  id                 :integer          not null, primary key
#  bird_id            :integer
#  birding_session_id :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  count              :integer
#  notes              :string
#  location           :geography({:srid point, 4326
#  time               :time
#

class BirdRecord < ApplicationRecord
  belongs_to :bird
  belongs_to :birding_session
  has_many :club_bird_records, dependent: :destroy
  has_many :clubs, through: :club_bird_records
  has_one :weather_report, through: :birding_session
  has_many :photos, as: :photographable

  scope :kilometres_from, -> (kilometres, location) { kilometres_from_session(kilometres, location).or(kilometres_from_record(kilometres, location)) }
  scope :kilometres_from_session, -> (kilometres, location) { joins(:birding_session).where('ST_DWithin(birding_sessions.location, Geography(ST_MakePoint(?, ?)), ?)', location.lon, location.lat, kilometres * 1000) }
  scope :kilometres_from_record, -> (kilometres, location) { joins(:birding_session).where('ST_DWithin(bird_records.location, Geography(ST_MakePoint(?, ?)), ?)', location.lon, location.lat, kilometres * 1000) }
  scope :order_by_time, -> { order('bird_records.time NULLS FIRST, bird_records.id') }
  scope :with_bird, -> { includes(:bird) }
  scope :within_area, -> (area) { joins(:birding_session).where('ST_Intersects(?, COALESCE(bird_records.location, birding_sessions.location))', area) }

  def bird_name
    bird.common_name
  end

  def date
    birding_session.date
  end

  def datetime
    return birding_session.datetime if time.nil?
    @datetime ||= DateTime.new(date.year, date.month, date.day, time.hour, time.min, time.sec, time.zone)
  end

  def location
    self[:location] || birding_session.location
  end

  def to_s
    "#{bird} - #{birding_session}"
  end
end

app/controllers/admin/bird_records_controller.rb
class Admin::BirdRecordsController < ApplicationController
  # GET /bird_records
  def index
    @bird_records = BirdRecord.all.page(params[:page])
  end

  # GET /bird_records/1
  def show
    @bird_record = BirdRecord.find(params[:id])
  end

  # GET /bird_records/new
  def new
    @bird_record = BirdRecord.new
  end

  # GET /bird_records/1/edit
  def edit
    @bird_record = BirdRecord.find(params[:id])
  end

  # POST /bird_records
  def create
    @bird_record = BirdRecord.new(bird_record_params)

    if @bird_record.save
      redirect_to admin_bird_records_url, notice: 'Bird record was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /bird_records/1
  def update
    @bird_record = BirdRecord.find(params[:id])

    if @bird_record.update(bird_record_params)
      redirect_to admin_bird_records_url, notice: 'Bird record was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bird_records/1
  def destroy
    @bird_record = BirdRecord.find(params[:id])

    @bird_record.destroy
    redirect_to admin_bird_records_url, notice: 'Bird record was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def bird_record_params
      params.require(:bird_record).permit(:bird_id, :birding_session_id, :count, :notes)
    end
end

app/views/admin/bird_records/_form.html.erb
<%= simple_form_for([:admin, @bird_record]) do |f| %>
  <%= f.error_notification %>

    <%= f.association :bird %>
    <%= f.input :count %>
    <%= f.input :notes %>
    <%= f.association :birding_session %>

  <%= f.button :submit %>
<% end %>

app/views/admin/bird_records/edit.html.erb
<%= page_header "Editing #{@bird_record.to_s}" %>

<div class="container">
  <div class="row">
  <div class="col-4">
      <%= render 'form', bird_record: @bird_record %>
    </div>
  </div>
</div>

app/views/admin/bird_records/index.html.erb
<%= page_header "Bird Records" %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <table class="table table-responsive">
        <thead>
          <tr>
            <th>Count</th>
            <th>Bird</th>
            <th>Notes</th>
            <th>Birding Session</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @bird_records.each do |bird_record| %>
            <tr>
              <td><%= bird_record.count %></td>
              <td><%= bird_record.bird %></td>
              <td><%= bird_record.notes %></td>
              <td><%= bird_record.birding_session %></td>
              <td class="text-right">
              <%= link_to 'Show', [:admin, bird_record], class: 'text-dark' %> |
              <%= link_to 'Edit', edit_admin_bird_record_path(bird_record), class: 'text-dark' %> |
              <%= link_to 'Destroy', [:admin, bird_record], method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= paginate @bird_records %>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <%= link_to 'Create New Bird Record', new_admin_bird_record_path, class: 'btn btn-outline-primary' %>
    </div>
  </div>
</div>

app/views/admin/bird_records/new.html.erb
<%= page_header "New Bird Record" %>

<div class="container">
  <div class="row">
    <div class="col-4">
      <%= render 'form', bird_record: @bird_record %>
    </div>
  </div>
</div>

app/views/admin/bird_records/show.html.erb
<%= page_header @bird_record %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <dl class="row">
        <dt class="col-sm-3">Count</dt>
        <dd class="col-sm-9"><%= @bird_record.count %></dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">Bird</dt>
        <dd class="col-sm-9"><%= link_to @bird_record.bird, [:admin, @bird_record.bird] %></dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">Notes</dt>
        <dd class="col-sm-9"><%= @bird_record.notes %></dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">Birding Session</dt>
        <dd class="col-sm-9"><%= link_to @bird_record.birding_session, [:admin, @bird_record.birding_session] %></dd>
      </dl>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <%= link_to 'Edit', [:edit, :admin, @bird_record], class: 'btn btn-outline-dark' %>
      <%= link_to 'Destroy', [:admin, @bird_record], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </div>
  </div>
</div>