config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  get '/add_bird_records', to: 'birding_sessions#new'
  resources :birding_sessions, only: [:new, :create, :edit, :update, :show]

  resources :clubs
  post '/clubs/:id/join', to: 'clubs#join', as: 'join_club'
  post '/clubs/:id/leave', to: 'clubs#leave', as: 'leave_club'
  get '/clubs/:id/members', to: 'clubs#members', as: 'club_members'
  get '/clubs/:id/membership', to: 'clubs#membership', as: 'club_membership'
  post '/clubs/:id/members/:user_id/roles', to: 'clubs#update_roles', as: 'update_club_roles'

  resources :photos, only: [:new, :create, :destroy]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  get 'user/clubs', to: 'user#clubs', as: 'user_clubs'

  get '/bird_lists/birds', to: 'bird_lists#birds'

  namespace :admin do
    root to: 'welcome#index'

    resources :bird_list_birds
    resources :bird_lists
    resources :bird_records
    resources :birding_sessions
    resources :birds
    resources :club_memberships
    resources :clubs
    resources :rarities
    resources :users

    mount Resque::Server.new, :at => "/resque"
  end

  root to: 'welcome#index'
end

app/models/rarity.rb
# == Schema Information
#
# Table name: rarities
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  level      :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Rarity < ApplicationRecord
  def to_s
    name
  end
end

app/controllers/admin/rarities_controller.rb
class Admin::RaritiesController < ApplicationController
  # GET /rarities
  def index
    @rarities = Rarity.all.page(params[:page])
  end

  # GET /rarities/1
  def show
    @rarity = Rarity.find(params[:id])
  end

  # GET /rarities/new
  def new
    @rarity = Rarity.new
  end

  # GET /rarities/1/edit
  def edit
    @rarity = Rarity.find(params[:id])
  end

  # POST /rarities
  def create
    @rarity = Rarity.new(rarity_params)

    if @rarity.save
      redirect_to admin_rarities_url, notice: 'Rarity was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /rarities/1
  def update
    @rarity = Rarity.find(params[:id])

    if @rarity.update(rarity_params)
      redirect_to admin_rarities_url, notice: 'Rarity was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /rarities/1
  def destroy
    @rarity = Rarity.find(params[:id])

    @rarity.destroy
    redirect_to admin_rarities_url, notice: 'Rarity was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def rarity_params
      params.require(:rarity).permit(:name, :level)
    end
end

app/views/admin/rarities/_form.html.erb
<%= simple_form_for([:admin, @rarity]) do |f| %>
  <%= f.error_notification %>

    <%= f.input :name %>
    <%= f.input :level %>

  <%= f.button :submit %>
<% end %>

app/views/admin/rarities/edit.html.erb
<%= page_header "Editing #{@rarity.to_s}" %>

<div class="container">
  <div class="row">
  <div class="col-4">
      <%= render 'form', rarity: @rarity %>
    </div>
  </div>
</div>

app/views/admin/rarities/index.html.erb
<%= page_header "Rarities" %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <table class="table table-responsive">
        <thead>
          <tr>
            <th>Name</th>
            <th>Level</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @rarities.each do |rarity| %>
            <tr>
              <td><%= rarity.name %></td>
              <td><%= rarity.level %></td>
              <td class="text-right">
              <%= link_to 'Show', [:admin, rarity], class: 'text-dark' %> |
              <%= link_to 'Edit', [:edit, :admin, rarity], class: 'text-dark' %> |
              <%= link_to 'Destroy', [:admin, rarity], method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= paginate @rarities %>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <%= link_to 'Create New Rarity', new_admin_rarity_path, class: 'btn btn-outline-primary' %>
    </div>
  </div>
</div>

app/views/admin/rarities/new.html.erb
<%= page_header "New Rarity" %>

<div class="container">
  <div class="row">
    <div class="col-4">
      <%= render 'form', rarity: @rarity %>
    </div>
  </div>
</div>

app/views/admin/rarities/show.html.erb
<%= page_header @rarity %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <dl class="row">
        <dt class="col-sm-3">Name</dt>
        <dd class="col-sm-9"><%= @rarity.name %></dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">Level</dt>
        <dd class="col-sm-9"><%= @rarity.level %></dd>
      </dl>
          </div>
  </div>
  <div class="row">
    <div class="col-12">
      <%= link_to 'Edit', [:edit, :admin, @rarity], class: 'btn btn-outline-dark' %>
      <%= link_to 'Destroy', [:admin, @rarity], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </div>
  </div>
</div>